name-template: '$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'pr:new feature'
  - title: '🔬 Improvements'
    label: 'pr:improvement'
  - title: '🐞 Bug Fixes'
    label: 'pr:bug'
  - title: '⬆️ Dependency Updates'
    label: 'pr:dependencies'
  - title: '📖 Documentation improvements'
    label: 'pr:documentation'
  - title: '⛔️ Security'
    label: 'pr:security'
  - title: '👻 Internal changes'
    label: 'pr:internal'

exclude-labels:
  - 'pr:invalid'
  - 'pr:tests'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES

  ## 👀 Links

  [Commits since $PREVIOUS_TAG](https://github.com/allure-framework/allure-python/compare/$PREVIOUS_TAG...master)
