name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 New Features'
    semver-increment: minor
    when:
      label: 'type:new feature'

  - title: '🔬 Improvements'
    when:
      label: 'type:improvement'

  - title: '🐞 Bug Fixes'
    when:
      label: 'type:bug'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES

  ## 👀 Links

  [Commits since $PREVIOUS_TAG](https://github.com/allure-framework/allure-python/compare/$PREVIOUS_TAG...master)