[tool.poe.tasks]
linter = "flake8 ./allure-*/src ./tests"
allure-generate = "allure generate --clean --output ./.allure-report ./.allure-results"
allure-open = "allure open ./.allure-report"

[tool.poe.tasks.tests]
cmd = "pytest"
env = { PYTEST_DISABLE_PLUGIN_AUTOLOAD = "true" }

[tool.poe.tasks.allure-collect]
cmd = "pytest -p allure_pytest --alluredir ./.allure-results --clean-alluredir --allure-link-pattern issue:https://github.com/allure-framework/allure-python/issues/{0}"
env = { PYTEST_DISABLE_PLUGIN_AUTOLOAD = "true" }

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
addopts = [
    "-p", "no:allure_pytest",
    "-p", "no:allure_pytest_bdd"
]
