[tool.poe.tasks]
linter = "flake8 ./allure-*/src ./tests"
tests = "pytest"

[tool.pytest.ini_options]
testpaths = [
    "tests"
]
addopts = [
    "-p", "no:allure_pytest",
    "-p", "no:allure_pytest_bdd"
]
