[tool.poe.tasks]
linter = "flake8 ./src"

[tool.poe.tasks.tests]
shell = "python -m doctest ./src/listener/utils.py && pytest ../tests/allure_robotframework"
env = { PYTEST_DISABLE_PLUGIN_AUTOLOAD = "true" }
