# -- FILE: behave.ini
[behave.formatters]
html-pretty = behave_html_pretty_formatter:PrettyHTMLFormatter
html = behave_html_formatter:HTMLFormatter
allure=allure_behave.formatter:AllureFormatter

[behave]
format=allure_behave.formatter:AllureFormatter
outfiles=allure-results
