name: release draft

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
